Traceback (most recent call last):
  File "C:\Users\gayan.gunaratne\.conda\envs\coastal\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\gayan.gunaratne\.conda\envs\coastal\lib\site-packages\nbclient\client.py", line 1265, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\gayan.gunaratne\.conda\envs\coastal\lib\site-packages\jupyter_core\utils\__init__.py", line 168, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\gayan.gunaratne\.conda\envs\coastal\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\gayan.gunaratne\.conda\envs\coastal\lib\site-packages\nbclient\client.py", line 703, in async_execute
    await self.async_execute_cell(
  File "C:\Users\gayan.gunaratne\.conda\envs\coastal\lib\site-packages\nbclient\client.py", line 1021, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\gayan.gunaratne\.conda\envs\coastal\lib\site-packages\nbclient\client.py", line 915, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Prompt the user to enter the date
date_input = input("Enter the date (YYYY-MM-DD): ")
year, month, day = map(int, date_input.split('-'))
# Call the get_tuflowtime function with the user's input
tuflowtime = get_tuflowtime(year, month, day)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mStdinNotImplementedError[0m                  Traceback (most recent call last)
Cell [1;32mIn[2], line 2[0m
[0;32m      1[0m [38;5;66;03m# Prompt the user to enter the date[39;00m
[1;32m----> 2[0m date_input [38;5;241m=[39m [38;5;28;43minput[39;49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mEnter the date (YYYY-MM-DD): [39;49m[38;5;124;43m"[39;49m[43m)[49m
[0;32m      3[0m year, month, day [38;5;241m=[39m [38;5;28mmap[39m([38;5;28mint[39m, date_input[38;5;241m.[39msplit([38;5;124m'[39m[38;5;124m-[39m[38;5;124m'[39m))
[0;32m      4[0m [38;5;66;03m# Call the get_tuflowtime function with the user's input[39;00m

File [1;32m~\.conda\envs\coastal\lib\site-packages\ipykernel\kernelbase.py:1186[0m, in [0;36mKernel.raw_input[1;34m(self, prompt)[0m
[0;32m   1184[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39m_allow_stdin:
[0;32m   1185[0m     msg [38;5;241m=[39m [38;5;124m"[39m[38;5;124mraw_input was called, but this frontend does not support input requests.[39m[38;5;124m"[39m
[1;32m-> 1186[0m     [38;5;28;01mraise[39;00m StdinNotImplementedError(msg)
[0;32m   1187[0m [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_input_request(
[0;32m   1188[0m     [38;5;28mstr[39m(prompt),
[0;32m   1189[0m     [38;5;28mself[39m[38;5;241m.[39m_parent_ident[[38;5;124m"[39m[38;5;124mshell[39m[38;5;124m"[39m],
[0;32m   1190[0m     [38;5;28mself[39m[38;5;241m.[39mget_parent([38;5;124m"[39m[38;5;124mshell[39m[38;5;124m"[39m),
[0;32m   1191[0m     password[38;5;241m=[39m[38;5;28;01mFalse[39;00m,
[0;32m   1192[0m )

[1;31mStdinNotImplementedError[0m: raw_input was called, but this frontend does not support input requests.
StdinNotImplementedError: raw_input was called, but this frontend does not support input requests.

